#Minecraft server properties
#Sun Jun 14 21:03:27 EDT 2026
view-distance=10
max-build-height=256
server-ip=
level-seed=
rcon.port=25575
allow-nether=true
server-port=25565
gamemode=0
enable-command-block=true
enable-rcon=true
enable-query=false
generator-settings=
enforce-secure-profile=true
rcon.password=changeme
level-name=world
player-idle-timeout=0
motd=\u00A7c\u00A7lBTWCE \u00A7r\u00A78| \u00A7eBetter Than Wolves\: Community Edition
force-gamemode=false
hardcore=false
white-list=false
pvp=true
texture-pack=
spawn-npcs=true
generate-structures=true
spawn-animals=true
snooper-enabled=false
difficulty=2
level-type=DEFAULT
max-tick-time=180000
spawn-monsters=true
max-players=20
enforce-whitelist=false
spawn-protection=0
online-mode=true
allow-flight=true
